package day17;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;



public class EmployeeDao {
	
	private final String TBL_EMPLOYEE = "employees";
	private final String COL_IDEMP = "idemp";
	private final String COL_EMPNUM = "empnum";
	private final String COL_EMPNAME = "empname";
	private final String COL_EMPGENDER = "empgender";
	private final String COL_EMPTELP = "emptelp";
	private final String COL_EMPADRESS = "empadress";
	
	public void creatTableEmployees() {
		DataSource ds = new DataSource();
		try {
			Statement statement = ds.getConnection().createStatement();
			statement.execute("CREATE TABLE IF NOT EXISTS public.employees (\r\n" + 
					"	idemp int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,\r\n" + 
					"	empnum varchar(25) NOT NULL,\r\n" +
					"	empname varchar(50) NOT NULL,\r\n" +
					"	empgender varchar(10) NOT NULL,\r\n" +
					"	emptelp varchar(14) NOT NULL,\r\n" +
					"	empadress varchar(50) NOT NULL,\r\n" +
					"	CONSTRAINT employees_pk PRIMARY KEY (idemp), \r\n" +
					"	CONSTRAINT employees_un UNIQUE (empnum)\r\n);");
			statement.close();
			ds.closeConnection();
			System.out.println("Table Employees created");
		} catch (SQLException e) {
			System.out.println("Create table failed! "+e.getMessage());
		}
	}
	
	public void insertEmployee(Employee emp) {
		DataSource ds = new DataSource();
		try {
			Statement statement = ds.getConnection().createStatement();
			statement.execute("INSERT INTO " + TBL_EMPLOYEE +
					"(" + COL_EMPNUM + "," +
					COL_EMPNAME + "," + COL_EMPGENDER + "," +
					COL_EMPTELP + "," +COL_EMPADRESS + 
					") Values " +
					"('" + emp.getEmpNumber() + "' ," +
					"'" + emp.getEmpName() + "' ," +
					"'" + emp.getEmpGender() + "' ," +
					"'" + emp.getEmpTelp() + "' ," +
					"'" + emp.getEmpAdress() + "');");
			statement.close();
			ds.closeConnection();
			System.out.println("Employee inserted");
		}catch (SQLException e) {
			System.out.println("Emplyee number already exist");
		}
	}
	
	public Employee getEmployee(String empNumber) {
		DataSource ds = new DataSource();
		Employee emp = new Employee();
		try {
			Statement statement = ds.getConnection().createStatement();
			String query = "SELECT * FROM "+ TBL_EMPLOYEE +
					" WHERE " + COL_EMPNUM + " = '" + empNumber + "'";
			ResultSet result = statement.executeQuery(query);
			while(result.next()) {
				emp.setIdEmp(result.getInt(COL_IDEMP));
				emp.setEmpNumber(result.getString(COL_EMPNUM));
				emp.setEmpName(result.getString(COL_EMPNAME));
				emp.setEmpGender(result.getString(COL_EMPGENDER));
				emp.setEmpTelp(result.getString(COL_EMPTELP));
				emp.setEmpAdress(result.getString(COL_EMPADRESS));
//				System.out.println(result.getString(COL_EMPNUM));
				statement.close();
				ds.closeConnection();
				return emp;
			}
			statement.close();
			ds.closeConnection();
		} catch (SQLException e) {
			System.out.println("Edit employee failed");
		}
		return null;
	}
	
	public Employee getEmpName(int idEmp) {
		DataSource ds = new DataSource();
		Employee emp = new Employee();
		try {
			Statement statement = ds.getConnection().createStatement();
			String query = "SELECT * FROM "+ TBL_EMPLOYEE +
					" WHERE " + COL_IDEMP + " = " + idEmp;
			ResultSet result = statement.executeQuery(query);
			while(result.next()) {
				emp.setIdEmp(result.getInt(COL_IDEMP));
				emp.setEmpNumber(result.getString(COL_EMPNUM));
				emp.setEmpName(result.getString(COL_EMPNAME));
				emp.setEmpGender(result.getString(COL_EMPGENDER));
				emp.setEmpTelp(result.getString(COL_EMPTELP));
				emp.setEmpAdress(result.getString(COL_EMPADRESS));
			}
			statement.close();
			ds.closeConnection();
			return emp;
		} catch (SQLException e) {
			System.out.println("Edit employee failed");
		}
		return null;
	}
	
	public void updateEmployee(Employee emp) {
		DataSource ds = new DataSource();
		try {
			Statement statement = ds.getConnection().createStatement();
			String query = "UPDATE " + TBL_EMPLOYEE +
					" SET " + COL_EMPNUM + " = '" + emp.getEmpNumber() + "', " +
					COL_EMPNAME + " = '" + emp.getEmpName() + "', " +
					COL_EMPGENDER + " = '" + emp.getEmpTelp() + "', " +
					COL_EMPADRESS + " = '" + emp.getEmpAdress() + "' " +
					"WHERE " + COL_IDEMP + " = '" + emp.getIdEmp() + "'";
			statement.execute(query);
			statement.close();
			ds.closeConnection();
			System.out.println("Employee edited");
		}catch (SQLException e) {
			System.out.println("Edit employee failed");
		}
	}
	
	public void deleteEmployee(String empNumber) {
		DataSource ds = new DataSource();
		try {
			Statement statement = ds.getConnection().createStatement();
			statement.execute("DELETE FROM " + TBL_EMPLOYEE +
					" WHERE " + COL_EMPNUM + " = '" + empNumber + "'");
			statement.close();
			ds.closeConnection();
			System.out.println("Employee deleted");
		} catch (SQLException e) {
			System.out.println("Delete employee failed "+e.getMessage());
		}
	}
	
	public void diplayEmployee() {
		DataSource ds = new DataSource();
		try {
			Statement statement = ds.getConnection().createStatement();
			ResultSet result = statement.executeQuery("SELECT * FROM " + TBL_EMPLOYEE);
			while(result.next()) {
				System.out.println("ID : "+ result.getInt(COL_IDEMP));
				System.out.println("Employee Number : "+ result.getString(COL_EMPNUM));
				System.out.println("Name : "+ result.getString(COL_EMPNAME));
				System.out.println("Gender : "+ result.getString(COL_EMPGENDER));
				System.out.println("No. Telp : "+ result.getString(COL_EMPTELP));
				System.out.println("Adress : "+ result.getString(COL_EMPADRESS));
				System.out.println();
			}
		} catch (SQLException e) {
			System.out.println("Gagal retrieve "+e.getMessage());
		}
	}

}
