package day17;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;


public class UserDao {
	
	private final String TBL_USERS = "users";
	private final String COL_IDUSER = "iduser";
	private final String COL_USERNAME = "username";
	private final String COL_PASSWORD = "password";
	private final String COL_IDEMPLOYEES = "idemp";
	private final String COL_IDROLES = "idroles";
	
	// table employee
	private final String TBL_EMPLOYEE = "employees";
	private final String COL_IDEMP = "idemp";
	private final String COL_EMPNUM = "empnum";
	private final String COL_EMPNAME = "empname";
	private final String COL_EMPGENDER = "empgender";
	private final String COL_EMPTELP = "emptelp";
	private final String COL_EMPADRESS = "empadress";
	
	// table role
	private final String TBL_ROLES = "roles";
	private final String COL_IDROLE = "idrole";
	private final String COL_ROLENAME = "rolename";
	
	public void createTableUsers() {
		DataSource ds = new DataSource();
		try {
			Statement statement = ds.getConnection().createStatement();
			statement.execute("CREATE TABLE IF NOT EXISTS public.users (\r\n" + 
					"	iduser int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,\r\n" + 
					"	username varchar(10) NOT NULL,\r\n" + 
					"	password varchar(25) NOT NULL,\r\n" + 
					"	idemployees int4 NOT NULL,\r\n" + 
					"	idroles int4 NOT NULL,\r\n" + 
					"	CONSTRAINT users_pk PRIMARY KEY (iduser),\r\n" + 
					"	CONSTRAINT user_un UNIQUE (username)\r\n" + 
					");\r\n" + 
					"\r\n" + 
					"ALTER TABLE public.users ADD CONSTRAINT users_fk FOREIGN KEY (idemployees) REFERENCES employees(idemp);" +
					"ALTER TABLE public.users ADD CONSTRAINT users_fk2 FOREIGN KEY (idroles) REFERENCES roles(idrole);" );
			statement.close();
			ds.closeConnection();
			System.out.println("Table User created!");
		} catch (SQLException e) {
			System.out.println("Create user failed "+e.getMessage());
		}
	}
	
	public void insertUser(User user) {
		DataSource ds = new DataSource();
		try {
			Statement statement = ds.getConnection().createStatement();
			statement.execute("INSERT INTO "+ TBL_USERS + 
						"(" + COL_USERNAME + "," +
						COL_PASSWORD + "," + 
						COL_IDEMPLOYEES + "," +
						COL_IDROLES + ") VALUES ( '" +
						user.getUsername() + "', '" +
						user.getPassword() + "', '" +
						user.getIdEmp() + "', '" +
						user.getIdRole() + "') ");
			statement.close();
			ds.closeConnection();
			System.out.println("User inserted");
		} catch (SQLException e) {
			System.out.println("Insert user failed! "+e.getMessage());
		}
	}
	
	public void updateUser(User user) {
		DataSource ds = new DataSource();
		try {
			Statement statement = ds.getConnection().createStatement();
			statement.execute("UPDATE " + TBL_USERS +
					" SET " + COL_USERNAME + " = '" + user.getUsername() + "' ," + 
					COL_PASSWORD + " = '" + user.getPassword() + "' ," +
					COL_IDEMPLOYEES + " = '" + user.getIdEmp() + "' ," +
					COL_IDROLES + " = '" + user.getIdRole() + "'" +
					" WHERE " + COL_IDUSER + " = " + user.getIdUser() );
			statement.close();
			ds.closeConnection();
			System.out.println("Data berhasil diubah");
		} catch (SQLException e) {
			System.out.println("Data gagal diubah "+e.getMessage());
		}
	}
	
	public void deleteUser(String username) {
		DataSource ds = new DataSource();
		try {
			Statement statement = ds.getConnection().createStatement();
			statement.execute("DELETE FROM " + TBL_USERS +
					" WHERE " + COL_USERNAME + " = '" + username + "'");
			statement.close();
			ds.closeConnection();
			System.out.println("Data berhasil dihapus");
		} catch (SQLException e) {
			System.out.println("Data gagal dihapus "+e.getMessage());
		}
	}
	
	public User cekUsername(String username) {
		DataSource ds = new DataSource();
		User user = new User();
		try {
			Statement statement = ds.getConnection().createStatement();
			ResultSet result = statement.executeQuery("SELECT * FROM " + TBL_USERS + 
					" WHERE " + COL_USERNAME + " = '" + username + "' ");
			while(result.next()) {
				user.setIdUser(result.getInt(COL_IDUSER));
				user.setUsername(result.getString(COL_USERNAME));
				user.setPassword(result.getString(COL_PASSWORD));
				user.setIdEmp(result.getInt(COL_IDEMPLOYEES));
				user.setIdRole(result.getInt(COL_IDROLES));
				statement.close();
				ds.closeConnection();
				return user;
			}
			statement.close();
			ds.closeConnection();
		} catch (SQLException e) {
			System.out.println("Username belum tedaftar");
		}
		return null;
	}
	
	
	public User login(User user) {
		DataSource ds = new DataSource();
		try {
			Statement statement = ds.getConnection().createStatement();
			ResultSet result = statement.executeQuery("SELECT * FROM " + TBL_USERS + 
					" WHERE " + COL_USERNAME + " = '" + user.getUsername() + "' " +
					"AND " + COL_PASSWORD + " = '" + user.getPassword() + "'");
			while(result.next()) {
				user.setIdUser(result.getInt(COL_IDUSER));
				user.setUsername(result.getString(COL_USERNAME));
				user.setPassword(result.getString(COL_PASSWORD));
				user.setIdEmp(result.getInt(COL_IDEMPLOYEES));
				user.setIdRole(result.getInt(COL_IDROLES));
//				user = new User(result.getInt(COL_IDUSER),
//						result.getString(COL_USERNAME), 
//						result.getString(COL_PASSWORD), 
//						result.getInt(COL_IDEMPLOYEES), 
//						result.getInt(COL_IDROLES));
//				user.setEmp(result.getInt(COL_IDEMP), 
//						result.getString(COL_EMPNUM), 
//						result.getString(COL_EMPNAME), 
//						result.getString(COL_EMPGENDER), 
//						result.getString(COL_EMPTELP), 
//						result.getString(COL_EMPADRESS));
//				user.setRole(result.getInt(COL_IDROLE), 
//						result.getString(COL_ROLENAME));
				statement.close();
				ds.closeConnection();
				return user;
			}
			statement.close();
			ds.closeConnection();
		} catch (SQLException e) {
			System.out.println("Login gagal " + e.getMessage());
		}
		
		return null;
	}
	
	public void diplayUser() {
		DataSource ds = new DataSource();
		try {
			Statement statement = ds.getConnection().createStatement();
			ResultSet result = statement.executeQuery("SELECT U.*, E.*, R.* FROM " + TBL_USERS + " AS U " +
					"JOIN " + TBL_EMPLOYEE + " AS E ON U." + COL_IDEMPLOYEES + " = E." + COL_IDEMP +
					" JOIN " + TBL_ROLES + " AS R ON U." + COL_IDROLES + " = R." + COL_IDROLE);
			while(result.next()) {
				System.out.println("ID : "+result.getInt(COL_IDUSER));
				System.out.println("Username : "+result.getString(COL_USERNAME));
				System.out.println("Employee Name : "+result.getString(COL_EMPNAME));
				System.out.println("Role : "+result.getString(COL_ROLENAME));
				System.out.println();
			}
		} catch (SQLException e) {
			System.out.println("Gagal retrieve "+e.getMessage());
		}
	}

			

}
